# Add a random record to Route53 for this domain
# Example: 123456789012_test.{domain}
# Deploy the app to lambda
# and link the domain to the lambda alias
# Example: 123456789012_test.{domain} -> 123456789012_test.{domain}.lambda

name: ci-deploy-test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Add a random record to Route53 for this domain
      # Example: 123456789012_test.{domain}
      - name: Add random record to Route53
        run: |
          aws route53 change-resource-record-sets \
            --hosted-zone-id ${{ secrets.HOSTED_ZONE_ID }} \
            --change-batch '{ "Comment": "Add random record to Route53", "Changes": [ { "Action": "CREATE", "ResourceRecordSet": { "Name": "'"$GITHUB_RUN_NUMBER"'_test.'"${{ secrets.DOMAIN }}"'", "Type": "A", "TTL": 300, "ResourceRecords": [ { "Value": "\
          '"$(curl -s http://